### ISSUE TITLE
Bump UnoCSS 0.53.4

### ISSUE THREAD

**Issue by eshimischi** [StarLederer/unocss-preset-mini-variants#2]
https://github.com/StarLederer/unocss-preset-mini-variants/blob/7427343b48d229e8d64b4accfc1cd7491e55627e/package.json#L44

Again, typings error. 0.53.4 need

**Comment by StarLederer** [comment]
I would recommend sticking to a supported version of UnoCSS to avoid type errors. Of course if there are big improvements I will update the package but I can't update and test it for every version at the moment which is why sometimes there can be a delay or a skipped version.

If you really need to update right now, if you are using pnpm, you can probably just force all packages to use the same version of UnoCSS by adding something like the following to your package.json
```json
"pnpm": {
  "overrides": {
    "unocss": "0.53.4",
    "@unocss/core": "0.53.4"
  }
}
```

**Comment by StarLederer** [comment]
By the way, if you could write integrations tests for this package I will setup CI that will automatically update this package to every version of UnoCSS for as long as there are no big changes. There is already an [issue](https://github.com/StarLederer/unocss-preset-mini-variants/issues/1) for this and I welcome contributions!

**Comment by eshimischi** [comment]
> I would recommend sticking to a supported version of UnoCSS to avoid type errors. Of course if there are big improvements I will update the package but I can't update and test it for every version at the moment which is why sometimes there can be a delay or a skipped version.
> 
> If you really need to update right now, if you are using pnpm, you can probably just force all packages to use the same version of UnoCSS by adding something like the following to your package.json
> 
> ```json
> "pnpm": {
>   "overrides": {
>     "unocss": "0.53.4",
>     "@unocss/core": "0.53.4"
>   }
> }
> ```

yes i've solved my issue for now. It is really strange that typings are sticked to versions and you have to upgrade it all the time.. Yes, it will be great to automate the process with CI, not sure if i can do it, but i'll try to search for similar solutions.
